-- ==========================================
-- 📊 MIGRATION: EDUCA CENSO PARA SCHOOL_INFO (COMPLETO V2)
-- Execute no SQL Editor do Supabase para atualizar a tabela
-- ==========================================

ALTER TABLE public.school_info 
-- Endereço e Identificação
ADD COLUMN IF NOT EXISTS cep TEXT,
ADD COLUMN IF NOT EXISTS director_cpf TEXT,
ADD COLUMN IF NOT EXISTS dependencia_adm TEXT DEFAULT 'Municipal',
ADD COLUMN IF NOT EXISTS situacao_func TEXT DEFAULT 'Em atividade',
ADD COLUMN IF NOT EXISTS forma_ocupacao TEXT DEFAULT 'Próprio',

-- Infra básica (V1)
ADD COLUMN IF NOT EXISTS infra_agua_rede BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS infra_agua_poco BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS infra_energia_rede BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS infra_esgoto_rede BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS infra_lixo_coleta BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS infra_internet BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS infra_banheiro_pne BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS alimentacao_escolar BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS atendimento_aee BOOLEAN DEFAULT FALSE,

-- Equipamentos (V1)
ADD COLUMN IF NOT EXISTS comp_admin INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS comp_alunos INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS impressoras INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS projetores INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tv INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS aparelho_som INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS internet_tipo TEXT DEFAULT 'Banda Larga',
ADD COLUMN IF NOT EXISTS acess_rampas BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS acess_elevador BOOLEAN DEFAULT FALSE,

-- 🏢 NOVOS CAMPOS: Dependências Físicas (V2)
ADD COLUMN IF NOT EXISTS sala_diretoria BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sala_professor BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS secretaria BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS almoxarifado BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS cozinha BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS despensa BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lavanderia BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS patio_coberto BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS patio_descoberto BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS parque_infantil BOOLEAN DEFAULT FALSE,

-- ♻️ NOVOS CAMPOS: Sustentabilidade e Resíduos (V2)
ADD COLUMN IF NOT EXISTS lixo_reciclagem BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS esgoto_fossa BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS lixo_destino TEXT DEFAULT 'Coleta pública',

-- ♿ NOVOS CAMPOS: Acessibilidade Detalhada (V2)
ADD COLUMN IF NOT EXISTS piso_tatil BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS corrimao BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS portais_largos BOOLEAN DEFAULT FALSE;
